# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_entry', models.IntegerField(unique=True, verbose_name='Log id')),
                ('lng', models.FloatField(verbose_name='Longitude')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
            ],
        ),
    ]
