# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(unique=True, verbose_name='Serial Number of IoT')),
                ('human_readable_name', models.TextField(verbose_name='Human readable name')),
                ('insert_date', models.DateTimeField(verbose_name='Insert Date')),
                ('type_of_device', models.CharField(choices=[('Fire Distinguisher', 'Fire Distinguisher'), ('Medi Kit', 'Medi Kit'), ('Fuse box', 'Fuse box'), ('Other', 'Other')], max_length=100, verbose_name='Type of a device')),
                ('last_check_date', models.DateTimeField(verbose_name='Last Check date')),
                ('location', models.CharField(max_length=100, verbose_name='GPS Location')),
                ('description_of_device', models.TextField(verbose_name='Description of a device')),
                ('description_of_content', models.TextField(verbose_name='Description of a content')),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Problem', 'Problem'), ('Broken', 'Broken'), ('Triggered', 'Triggered'), ('Other', 'Other')], max_length=100, verbose_name='Status')),
                ('posted', models.BooleanField(default=False, verbose_name='Posted')),
            ],
        ),
    ]
