# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip_addrr',
            field=models.GenericIPAddressField(default='0.0.0.0.', verbose_name='IP addrres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='port',
            field=models.IntegerField(default=22, verbose_name='Port'),
            preserve_default=False,
        ),
    ]
