# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20160305_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='human_readable_name',
            field=models.CharField(max_length=100, verbose_name='Human readable name'),
        ),
    ]
