# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20160305_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type_of_device',
            field=models.CharField(choices=[('FD', 'Fire Distinguisher'), ('MK', 'Medi Kit'), ('FB', 'Fuse box'), ('O', 'Other')], max_length=100, verbose_name='Type of a device'),
        ),
    ]
